In [1]:
import numpy as np 
import pandas as pd 

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [2]:
movies = pd.read_csv("C:\\Users\\Vinutha TJ\\Downloads\\archive (4)\\tmdb_5000_movies.csv")
credits = pd.read_csv("C:\\Users\\Vinutha TJ\\Downloads\\archive (4)\\tmdb_5000_credits.csv")

In [3]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [4]:
movies.shape

(4803, 20)

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies = movies.merge(credits,on='title')

In [7]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [9]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
import ast

In [11]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [12]:
movies.dropna(inplace=True)

In [13]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [15]:
import ast

In [16]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [17]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [19]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [20]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [21]:
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
4709,39141,Tadpole,"Beautiful, sophisticated women are all over Os...","[Comedy, Drama, Romance]",[independent film],"[Aaron Stanford, Kate Mara, Bebe Neuwirth]",[Gary Winick]
2813,56601,The Perfect Game,"Based on a true story, a group of boys from Mo...","[Drama, Family]","[baseball, sport, based on true story, family ...","[Clifton Collins Jr, Cheech Marin, Moisés Arias]",[William Dear]
1378,11638,Guess Who,The fiancé of an African-American woman who's ...,"[Comedy, Romance]","[black people, jealousy, parents-in-law, troub...","[Bernie Mac, Ashton Kutcher, Zoe Saldana]",[Kevin Rodney Sullivan]
137,49444,Kung Fu Panda 2,Po is now living his dream as The Dragon Warri...,"[Animation, Family]","[martial arts, hope, fleet, panda, mission, wo...","[Jack Black, Angelina Jolie, Dustin Hoffman]",[Jennifer Yuh Nelson]
1465,26843,Lion of the Desert,"This movie tells the story of Omar Mukhtar, an...","[Action, History, War]","[italy, middle east, resistance, world war ii,...","[Anthony Quinn, Rod Steiger, Oliver Reed]",[Moustapha Akkad]

In [22]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [23]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [24]:
movies.head(35)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]
5,559,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,"[Fantasy, Action, Adventure]","[dualidentity, amnesia, sandstorm, loveofone's...","[TobeyMaguire, KirstenDunst, JamesFranco]",[SamRaimi]
6,38757,Tangled,When the kingdom's most wanted-and most charmi...,"[Animation, Family]","[hostage, magic, horse, fairytale, musical, pr...","[ZacharyLevi, MandyMoore, DonnaMurphy]","[ByronHoward, NathanGreno]"
7,99861,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,"[Action, Adventure, ScienceFiction]","[marvelcomic, sequel, superhero, basedoncomicb...","[RobertDowneyJr., ChrisHemsworth, MarkRuffalo]",[JossWhedon]
8,767,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...","[Adventure, Fantasy, Family]","[witch, magic, broom, schoolofwitchcraft, wiza...","[DanielRadcliffe, RupertGrint, EmmaWatson]",[DavidYates]
9,209112,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,"[Action, Adventure, Fantasy]","[dccomics, vigilante, superhero, basedoncomicb...","[BenAffleck, HenryCavill, GalGadot]",[ZackSnyder]
10,1452,Superman Returns,Superman returns to discover his 5-year absenc...,"[Adventure, Fantasy, Action, ScienceFiction]","[savingtheworld, dccomics, invulnerability, se...","[BrandonRouth, KevinSpacey, KateBosworth]",[BryanSinger]
11,10764,Quantum of Solace,Quantum of Solace continues the adventures of ...,"[Adventure, Action, Thriller, Crime]","[killing, undercover, secretagent, britishsecr...","[DanielCraig, OlgaKurylenko, MathieuAmalric]",[MarcForster]
12,58,Pirates of the Caribbean: Dead Man's Chest,Captain Jack Sparrow works his way out of a bl...,"[Adventure, Fantasy, Action]","[witch, fortuneteller, bondage, exoticisland, ...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
13,57201,The Lone Ranger,The Texas Rangers chase down a gang of outlaws...,"[Action, Adventure, Western]","[texas, horse, survivor, texasranger, partner,...","[JohnnyDepp, ArmieHammer, WilliamFichtner]",[GoreVerbinski]
14,49521,Man of Steel,A young boy learns that he has extraordinary p...,"[Action, Adventure, Fantasy, ScienceFiction]","[savingtheworld, dccomics, superhero, basedonc...","[HenryCavill, AmyAdams, MichaelShannon]",[ZackSnyder]
15,2454,The Chronicles of Narnia: Prince Caspian,One year after their incredible adventures in ...,"[Adventure, Family, Fantasy]","[basedonnovel, fictionalplace, brothersisterre...","[BenBarnes, WilliamMoseley, AnnaPopplewell]",[AndrewAdamson]
16,24428,The Avengers,When an unexpected enemy emerges and threatens...,"[ScienceFiction, Action, Adventure]","[newyork, shield, marvelcomic, superhero, base...","[RobertDowneyJr., ChrisEvans, MarkRuffalo]",[JossWhedon]
17,1865,Pirates of the Caribbean: On Stranger Tides,Captain Jack Sparrow crosses paths with a woma...,"[Adventure, Action, Fantasy]","[sea, captain, mutiny, sword, primeminister, s...","[JohnnyDepp, PenélopeCruz, IanMcShane]",[RobMarshall]
18,41154,Men in Black 3,Agents J (Will Smith) and K (Tommy Lee Jones) ...,"[Action, Comedy, ScienceFiction]","[timetravel, timemachine, alien, fictionalgove...","[WillSmith, TommyLeeJones, JoshBrolin]",[BarrySonnenfeld]
19,122917,The Hobbit: The Battle of the Five Armies,Immediately after the events of The Desolation...,"[Action, Adventure, Fantasy]","[corruption, elves, dwarves, orcs, middle-eart...","[MartinFreeman, IanMcKellen, RichardArmitage]",[PeterJackson]
20,1930,The Amazing Spider-Man,Peter Parker is an outcast high schooler aband...,"[Action, Adventure, Fantasy]","[lossoffather, vigilante, serum, marvelcomic, ...","[AndrewGarfield, EmmaStone, RhysIfans]",[MarcWebb]
21,20662,Robin Hood,When soldier Robin happens upon the dying Robe...,"[Action, Adventure]","[robinhood, archer, knight, sherwoodforest, bo...","[RussellCrowe, CateBlanchett, MaxvonSydow]",[RidleyScott]
22,57158,The Hobbit: The Desolation of Smaug,"The Dwarves, Bilbo and Gandalf have successful...","[Adventure, Fantasy]","[elves, dwarves, orcs, hobbit, dragon, wizard,...","[MartinFreeman, IanMcKellen, RichardArmitage]",[PeterJackson]
23,2268,The Golden Compass,"After overhearing a shocking secret, precociou...","[Adventure, Fantasy]","[england, compass, experiment, lordship, uncle...","[DakotaBlueRichards, NicoleKidman, DanielCraig]",[ChrisWeitz]
24,254,King Kong,"In 1933 New York, an overly ambitious movie pr...","[Adventure, Drama, Action]","[filmbusiness, screenplay, showbusiness, filmm...","[NaomiWatts, JackBlack, AdrienBrody]",[PeterJackson]
25,597,Titanic,"84 years later, a 101-year-old woman named Ros...","[Drama, Romance, Thriller]","[shipwreck, iceberg, ship, panic, titanic, oce...","[KateWinslet, LeonardoDiCaprio, FrancesFisher]",[JamesCameron]
26,271110,Captain America: Civil War,"Following the events of Age of Ultron, the col...","[Adventure, Action, ScienceFiction]","[civilwar, war, marvelcomic, sequel, superhero...","[ChrisEvans, RobertDowneyJr., ScarlettJohansson]","[AnthonyRusso, JoeRusso]"
27,44833,Battleship,"When mankind beams a radio signal into space, ...","[Thriller, Action, Adventure, ScienceFiction]","[fight, u.s.navy, mindreading, hongkong, socce...","[TaylorKitsch, AlexanderSkarsgård, Rihanna]",[PeterBerg]
28,135397,Jurassic World,Twenty-two years after the events of Jurassic ...,"[Action, Adventure, ScienceFiction, Thriller]","[monster, dna, tyrannosaurusrex, velociraptor,...","[ChrisPratt, BryceDallasHoward, IrrfanKhan]",[ColinTrevorrow]
29,37724,Skyfall,When Bond's latest assignment goes gravely wro...,"[Action, Adventure, Thriller]","[spy, secretagent, sociopath, killer, artgalle...","[DanielCraig, JudiDench, JavierBardem]",[SamMendes]
30,558,Spider-Man 2,Peter Parker is going through a major identity...,"[Action, Adventure, Fantasy]","[dualidentity, loveofone'slife, pizzaboy, marv...","[TobeyMaguire, KirstenDunst, JamesFranco]",[SamRaimi]
31,68721,Iron Man 3,When Tony Stark's world is torn apart by a for...,"[Action, Adventure, ScienceFiction]","[terrorist, waronterror, tennessee, malibu, ma...","[RobertDowneyJr., GwynethPaltrow, DonCheadle]",[ShaneBlack]
32,12155,Alice in Wonderland,"Alice, an unpretentious and individual 19-year...","[Family, Fantasy, Adventure]","[basedonnovel, fictionalplace, queen, fantasy,...","[MiaWasikowska, JohnnyDepp, AnneHathaway]",[TimBurton]
33,36668,X-Men: The Last Stand,"When a cure is found to treat mutations, lines...","[Adventure, Action, ScienceFiction, Thriller]","[mutant, marvelcomic, basedoncomicbook, superh...","[HughJackman, HalleBerry, IanMcKellen]",[BrettRatner]
34,62211,Monsters University,A look at the relationship between Mike and Su...,"[Animation, Family]","[monster, dormitory, games, animation, bestfri...","[BillyCrystal, JohnGoodman, SteveBuscemi]",[DanScanlon]

In [25]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [26]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [27]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])

In [28]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [30]:
vector = cv.fit_transform(new['tags']).toarray()

In [31]:
vector.shape

(4806, 5000)

In [32]:
from sklearn.metrics.pairwise import cosine_similarity

In [33]:
similarity = cosine_similarity(vector)

In [34]:
similarity

array([[1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
        0.        ],
       [0.08964215, 1.        , 0.06350006, ..., 0.02635231, 0.        ,
        0.        ],
       [0.06071767, 0.06350006, 1.        , ..., 0.02677398, 0.        ,
        0.        ],
       ...,
       [0.02519763, 0.02635231, 0.02677398, ..., 1.        , 0.07352146,
        0.04774099],
       [0.0277885 , 0.        , 0.        , ..., 0.07352146, 1.        ,
        0.05264981],
       [0.        , 0.        , 0.        , ..., 0.04774099, 0.05264981,
        1.        ]])

In [35]:
def recommend(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[0:6]:
        print(new.iloc[i[0]].title)

In [36]:
recommend('''Titanic''')

Titanic
Captain Phillips
The Notebook
In the Heart of the Sea
Ghost Ship
Poseidon

In [37]:
import pickle

In [38]:
pickle.dump(new,open('movies.pkl','wb'))

In [40]:
new['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [42]:
pickle.dump(new.to_dict(),open('movie_dict.pkl','wb'))

In [44]:
pickle.dump(similarity,open('similarity.pkl','wb'))